[colors.primary]
background = "#111c18"
foreground = "#C1C497"

[colors.cursor]
text = "#111c18"
cursor = "#D7C995"

[colors.vi_mode_cursor]
text = "#111c18"
cursor = "#D7C995"

[colors.search.matches]
foreground = "#111c18"
background = "#459451"

[colors.search.focused_match]
foreground = "#111c18"
background = "#FF5345"

[colors.footer_bar]
foreground = "#111c18"
background = "#C1C497"

[colors.selection]
text = "#111C18"
background = "#C1C497"

[colors.normal]
black = "#23372B"
red = "#FF5345"
green = "#549e6a"
yellow = "#459451"
blue = "#509475"
magenta = "#D2689C"
cyan = "#2DD5B7"
white = "#F6F5DD"

[colors.bright]
black = "#53685B"
red = "#db9f9c"
green = "#63b07a"
yellow = "#E5C736"
blue = "#ACD4CF"
magenta = "#75bbb3"
cyan = "#8CD3CB"
white = "#9eebb3"
